"""baseline reset

Revision ID: 1cf6a4584062
Revises: 
Create Date: 2026-02-18 05:25:43.222821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf6a4584062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_member_phone_per_gym'), type_='unique')
        batch_op.create_unique_constraint('uq_member_phone_per_gym', ['gym_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_phone_per_gym', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_member_phone_per_gym'), ['gym_id', 'phone_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
