"""empty message

Revision ID: 392fd5013cd2
Revises: 9de9947b6f9b
Create Date: 2026-02-23 12:45:13.919173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392fd5013cd2'
down_revision = '9de9947b6f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
