"""fixing member model

Revision ID: a7eb8f07131f
Revises: 1cf6a4584062
Create Date: 2026-02-18 05:35:08.795024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7eb8f07131f'
down_revision = '1cf6a4584062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_member_phone_per_gym'), type_='unique')
        batch_op.create_index('uq_member_phone_per_gym', ['gym_id', 'phone_number'], unique=True, postgresql_where=sa.text('phone_number IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('uq_member_phone_per_gym', postgresql_where=sa.text('phone_number IS NOT NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_member_phone_per_gym'), ['gym_id', 'phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
