"""Initial Commit

Revision ID: 0f7de772f6c5
Revises: 
Create Date: 2026-01-16 09:17:10.631136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7de772f6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gyms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gyms_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gyms_is_active'))
        batch_op.drop_index(batch_op.f('ix_gyms_created_at'))

    op.drop_table('gyms')
    # ### end Alembic commands ###
