"""Sixth Commit

Revision ID: 23ba51573930
Revises: b2168d4cb03f
Create Date: 2026-01-20 05:49:02.189772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ba51573930'
down_revision = 'b2168d4cb03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_memberships_gym_id'), ['gym_id'], unique=False)
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_payments_gym_id'), ['gym_id'], unique=False)
        batch_op.create_foreign_key(None, 'gyms', ['gym_id'], ['id'])

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_plans_name'))
        batch_op.create_index(batch_op.f('ix_plans_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_name'))
        batch_op.create_index(batch_op.f('ix_plans_name'), ['name'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_gym_id'))
        batch_op.drop_column('gym_id')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_memberships_gym_id'))
        batch_op.drop_column('gym_id')

    # ### end Alembic commands ###
